#!/sbin/sh
> /tmp/configs
busybox find /dev/block -type l | busybox sed '/mmcblk/d' | busybox xargs -n 1 busybox ls -l | busybox sed '/mmcblk/!d;s/.*[ \t][ \t]*\([^ \t][^ \t]*\)[ \t][ \t]*->[ \t][ \t]*\([^ \t][^ \t]*\)$/\1=\2/' | busybox sed 's/^\(.\)/\/\1/;s/=/=\//;s/.*\/\([^=\/][^=\/]*\)=\/\(.*\)/\1=\2/;/^p[0-9]/d' | busybox sort -u | busybox sed '/^$/d'  >> /tmp/configs
if [ -z "$(busybox cat /tmp/configs)" ]; then
	busybox awk '{ print $1" ""="" "$3 }' $(busybox grep -r "\/boot" /etc | busybox sed 's/:.*//') | busybox sed 's/^\///; /#/d' > /tmp/configs
fi
for i in kern-a android_boot kernel lnx boot_a bootimg
do
	busybox sed -i "s/$i=/boot=/g" /tmp/configs
done
